defmodule Tunez.Repo.Migrations.ArtistBio do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:artists) do
      add :biography, :text
    end
  end

  def down do
    alter table(:artists) do
      remove :biography
    end
  end
end
